#version: '3'

#services:
#  mysql-standalone:
#    image: mysql:latest
#    container_name: mysql-standalone
#    environment:
##      - MYSQL_ROOT_PASSWORD=admin@123
#      - MYSQL_DATABASE=springboot
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=pass@word1
#  springboot-docker-container:
#    image: springboot-docker-container
#    container_name: springboot-docker-container
#    ports:
#      - 8080:8080
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - mysql-standalone

version: '3.3'

services:
  db:
    image: mysql:latest
    build: ./mysql
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=pass@word1
    ports:
      - "8083:3306"

  demo:
    image: springboot-docker-container
    build: .
    container_name: springboot-docker-container
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/springboot
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass@word1
